Add "containerElement" API documentation
trellisconnect/js-sdk-docs pull request #16
Opened 2021-11-02 20:53 UTC by frankieramirez

Added a new option to add a container element in which the Trellis Widget gets embedded. By default, the widget's iframe gets appended as a child of the `<body>`. 

Added some notes explaining how the new property functions and added an example of how `document.querySelector()` can be used to pass in the desired element.

2021-11-02 20:54 UTC, frankieramirez commented
@zachwills I just realized prettier changed all the " to '. Do we want to keep all strings using double quotes?

2021-11-03 14:36 UTC, zachwills commented
@frankieramirez yea let's keep it as-is to minimize unnecessary noise in the diffs

2021-11-03 14:40 UTC, zachwills commented on README.md
> +      // We recommend you add the style `position: realtive` to the container element if you wish the iframe to be contained within the container element.
change `wish` to `want`

2021-11-03 14:41 UTC, zachwills requested changes

2021-11-03 14:41 UTC, zachwills commented on README.md
> +      // The iframe overlay is absolutely positioned and will otherwise span outside of the container.
Let's not say `iframe` anywhere, let's keep it simple and say `Trellis Widget overlay`

2021-11-03 14:53 UTC, frankieramirez commented on README.md
> +      // We recommend you add the style `position: realtive` to the container element if you wish the iframe to be contained within the container element.
Thanks

2021-11-03 19:20 UTC, zachwills approved these changes

2021-11-03 19:20 UTC, merged